name: a_star
description: A sample A* algorithm built with Dart.
author: Seth Ladd <sethladd@gmail.com>
homepage: https://github.com/sethladd/dart-a-star
version: 0.3.0
dependencies:
dev_dependencies:
  benchmark_harness: any
  test: any
